/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package block_de_notasbeans.vistas;

import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaH extends javax.swing.JFrame {


    /**
     * Creates new form VentanaH
     */
    public VentanaH() {

        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println("Iniciando Ventana Halloween!");
//        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLateral = new javax.swing.JPanel();
        PanelNorte = new javax.swing.JPanel();
        btnCopiar = new javax.swing.JButton();
        btnCortar = new javax.swing.JButton();
        btnPegar = new javax.swing.JButton();
        PanelSur = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        PanelCentral = new javax.swing.JPanel();
        txtEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTextoPrincipal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        PanelLateral.setBackground(new java.awt.Color(51, 0, 51));
        PanelLateral.setLayout(new java.awt.BorderLayout());

        PanelNorte.setBackground(new java.awt.Color(51, 0, 51));
        PanelNorte.setLayout(new javax.swing.BoxLayout(PanelNorte, javax.swing.BoxLayout.Y_AXIS));

        btnCopiar.setBackground(new java.awt.Color(51, 0, 51));
        btnCopiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCopiar.setForeground(java.awt.Color.orange);
        btnCopiar.setText("Copiar");
        btnCopiar.setBorder(null);
        btnCopiar.setFocusable(false);
        btnCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelNorte.add(btnCopiar);

        btnCortar.setBackground(new java.awt.Color(51, 0, 51));
        btnCortar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCortar.setForeground(java.awt.Color.orange);
        btnCortar.setText("Cortar");
        btnCortar.setBorder(null);
        btnCortar.setFocusable(false);
        btnCortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelNorte.add(btnCortar);

        btnPegar.setBackground(new java.awt.Color(51, 0, 51));
        btnPegar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPegar.setForeground(java.awt.Color.orange);
        btnPegar.setText("Pegar");
        btnPegar.setBorder(null);
        btnPegar.setFocusable(false);
        btnPegar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPegar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelNorte.add(btnPegar);

        PanelLateral.add(PanelNorte, java.awt.BorderLayout.NORTH);

        PanelSur.setBackground(new java.awt.Color(51, 0, 51));
        PanelSur.setLayout(new javax.swing.BoxLayout(PanelSur, javax.swing.BoxLayout.Y_AXIS));

        btnNuevo.setBackground(new java.awt.Color(51, 0, 51));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(java.awt.Color.orange);
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelSur.add(btnNuevo);

        btnSalir.setBackground(new java.awt.Color(51, 0, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setForeground(java.awt.Color.orange);
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelSur.add(btnSalir);

        PanelLateral.add(PanelSur, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelLateral, java.awt.BorderLayout.LINE_END);

        PanelCentral.setBackground(new java.awt.Color(51, 0, 51));
        PanelCentral.setLayout(new java.awt.BorderLayout());

        txtEstado.setBackground(new java.awt.Color(51, 0, 51));
        txtEstado.setForeground(new java.awt.Color(204, 0, 0));
        txtEstado.setText("Iniciando...");
        txtEstado.setOpaque(true);
        PanelCentral.add(txtEstado, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setBorder(null);

        AreaTextoPrincipal.setBackground(new java.awt.Color(51, 0, 51));
        AreaTextoPrincipal.setColumns(20);
        AreaTextoPrincipal.setForeground(new java.awt.Color(255, 0, 0));
        AreaTextoPrincipal.setRows(5);
        AreaTextoPrincipal.setBorder(null);
        jScrollPane1.setViewportView(AreaTextoPrincipal);

        PanelCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 640, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaTextoPrincipal;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelNorte;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnCortar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPegar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtEstado;
    // End of variables declaration//GEN-END:variables

    public void ClickMitemCopiar(ActionListener l) {
        btnCopiar.addActionListener(l);
    }

    public void ClickMitemCortar(ActionListener l) {
        btnCortar.addActionListener(l);
    }

    public void ClickMitemPegar(ActionListener l) {
        btnPegar.addActionListener(l);
    }

    public void ClickBtnNuevo(ActionListener l) {
        btnNuevo.addActionListener(l);
    }

    public void ClickBtnSalir(ActionListener l) {
        btnSalir.addActionListener(l);
    }



    public void SMS(String MSM, String Titulo) {
        JOptionPane.showMessageDialog(null,MSM,Titulo, JOptionPane.WARNING_MESSAGE);
    }

    public void Estado(String MSM) {
        txtEstado.setText(MSM);
    }

    public void ponAreaTextoPrincipal(String Cosa) {
        AreaTextoPrincipal.setText(Cosa);
    }

public void fuenteAreaTextoPrincipal(Font Cosa) {
        AreaTextoPrincipal.setFont(Cosa);
    }

/*
    public JButton getBtnCasiMVC() {
        return btnCasiMVC;
    }

    public void setBtnCasiMVC(JButton btnCasiMVC) {
        this.btnCasiMVC = btnCasiMVC;
    }
*/

}


